### ISSUE TITLE
Harsh needs to bring Kyubey backpack to UTD!

### ISSUE THREAD

**Issue by Kappacitance** [plasmeus/Mystical-Slime-RPG#2]
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!
Harsh needs to bring Kyubey backpack to UTD!

**Comment by mr-narwhal** [comment]
Already done...
